import type { Metadata } from "next";
// import {  Geist_Mono } from "next/font/google";
import "./globals.css";
import AuthProvider from '@/components/AuthProvider';
import ClientLayoutWrapper from "@/components/ClientLayoutWrapper";
import { getCart } from "./action";
import { auth } from "@/auth";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    const [initialCart, session] = await Promise.all([
    getCart(),
    auth(),
  ]);
console.log(session)

  return (
    <html lang="en">
      <body
        className={` antialiased`}
      >
        <AuthProvider>
          <ClientLayoutWrapper session={session} initialCart={initialCart}  >
            {children}
          </ClientLayoutWrapper>

        </AuthProvider>
     
      </body>
    </html>
  );
}
